### PR TITLE
Jeremy zhuang/hw1

### PR DESCRIPTION
**Pull request by soutou233**
### Files added
- MavenProject/Hw1/.gitignore
- MavenProject/Hw1/pom.xml
- MavenProject/Hw1/src/main/java/org/example/Main.java
- ShortQuestions/README.md
- ShortQuestions/hw1.md

### CODE REVIEW

**Comment by hzl1183** [comment]
nice work

**Comment by minHe1117** [comment]
good job!

**Comment by Hidoikoto** [comment]
What’s the .gitignore file used for?

**Comment by soutou233** [comment]
> What’s the .gitignore file used for?

for the files that you want git to ignore to add/commit

**Pull request merged**
